site_name: UGM Framework Guideline
site_description: Pedoman pengembangan sistem di UGM
site_url: http://dti.ugm.ac.id
site_author: Task Force UGM Framework DTI UGM
theme:
  name: material
  palette:
    primary: indigo
  logo: assets/ugmfw.png
  favicon: assets/favicon.ico
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.progress
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.path
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - toc.follow
plugins:
  - search
  - blog
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
repo_url: https://git.dev.ugm.ac.id/ugmfw/guidelines
repo_name: ugmfw/guidelines
extra:
  generator: false
  version:
    provider: mike
copyright: Copyright &copy; 2024 Universitas Gadjah Mada | Made with ❤️ and ☕ by Direktorat Teknologi Informasi.
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - Beranda:
      - UGM Framework: index.md
      - Tujuan: tujuan.md
      - Penutup: closing.md
  - Arsitektur & Prinsip:
      - Arsitektur Sistem: arsitektur-prinsip/arsitektur-sistem.md
      - Prinsip Dasar Pengembangan: arsitektur-prinsip/prinsip-dasar-pengembangan.md
      - Konsistensi Teknologi: arsitektur-prinsip/konsistensi-teknologi.md
      - Clean Code: arsitektur-prinsip/clean-code.md
  - PHP:
      - Intro: psr/intro.md
      - PSR 1: psr/psr-1.md
      - PSR 12: psr/psr-12.md
      - PSR 4: psr/psr-4.md
      - PSR 3: psr/psr-3.md
      - PSR 7: psr/psr-7.md
      - PSR 15: psr/psr-15.md
      - PSR 17: psr/psr-17.md
      - PSR 18: psr/psr-18.md
      - PSR 11: psr/psr-11.md
      - PSR 13: psr/psr-13.md
      - PSR 6: psr/psr-6.md
      - PSR 16: psr/psr-16.md
      - PSR 14: psr/psr-14.md
      - PSR 5: psr/psr-5.md
  - API:
      - Pilar-pilar API: api/pilar-pilar-api.md
      - Framework API: api/framework-api.md
      - Struktur Dasar API: api/struktur-dasar-api.md
      - Metode HTTP: api/metode-http-api.md
      - Format Response API: api/format-response-api.md
      - Data Validation & Sanitization: api/validasi-sanitasi.md
      - Pagination, Filtering, & Sorting: api/pagination-filtering-sorting.md
      - Keamanan: api/security-api.md
      - Scopes: api/scopes.md
      - Versioning Database: api/orm-database.md
      - Cache: api/cache-api.md
  - API Gateway:
      - Intro: api_gateway/pengantar.md
      - KrakenD:
          - Apa itu KrakenD?: api_gateway/karakend_api_gateway.md
          - Menggunakan KrakenD: api_gateway/menggunakan_krakend.md
          - Fungsi Lain dari KrakenD: api_gateway/fungsi_lain_krakend.md
          - Flexibel Configuration: api_gateway/krakend_fastapi.md
  - Python:
      - PEP8: python/pedoman.md
      - FastAPI: python/praktik.md
      - Dokumentasi API: python/integrasi.md
  - Dokumentasi:
      - Dokumentasi: dokumentasi/dokumentasi-content.md
      - Changelog: dokumentasi/changelog-content.md
  - Database:
      - Intro Database: database/intro.md
      - Basis Data: database/penamaan-db.md
      - Struktur Tabel: database/penamaan-table-view-dll.md
      - Penamaan Field: database/penamaan-field.md
      - Data Staff & Student: database/database-staff-student.md
      - Transaksi & Referensi: database/aturan-data-transaksi-referensi.md
  - DEVOPS: devops/devops.md
  - Keamanan:
      - Intro: security/intro.md
      - Celah Keamanan:
          - Intro: security/intro-celah-keamanan.md
          - SQL Injection: security/sql-injection.md
          - Cross-site Scripting: security/cross-site-scripting.md
          - Cross-site Request Forgery: security/cross-site-request-forgery.md
          - Path Traversal: security/path-traversal.md
          - Command Injection: security/command-injection.md
          - Broken Access Control: security/broken-access-control.md
          - Sensitive Data Exposure: security/sensitive-data-exposure.md
      - Pengujian Keamanan:
          - Intro: security/intro-pengujian.md
          - SAST: security/sast.md
          - DAST: security/dast.md
  - Contact: contact.md
