site_name: UGM Framework Guideline
site_description: Pedoman pengembangan sistem di UGM
site_url: http://dti.ugm.ac.id
site_author: Task Force UGM Framework DTI UGM
theme:
  name: material
  palette:
    primary: indigo
  logo: assets/ugmfw.png
  favicon: assets/favicon.ico
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.progress
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.path
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - toc.follow
plugins:
  - search
  - blog
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
repo_url: https://git.dev.ugm.ac.id/ugmfw/guidelines
repo_name: ugmfw/guidelines
extra:
  generator: false
  version:
    provider: mike
copyright: Copyright &copy; 2024 Universitas Gadjah Mada | Made with ❤️ and ☕ by Direktorat Teknologi Informasi.
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - Beranda:
      - UGM Framework: index.md
      - Tujuan: tujuan.md
  - Arsitektur & Prinsip:
      - Arsitektur Sistem: arsitektur-sistem.md
      - Prinsip Dasar Pengembangan: prinsip-dasar-pengembangan.md
      - Konsistensi Teknologi: konsistensi-teknologi.md
      - Clean Code: clean-code.md
  - PHP:
      - Intro: psr/intro.md
      - PSR 1: psr/psr-1.md
      - PSR 2: psr/psr-2.md
      - PSR 3: psr/psr-3.md
      - PSR 4: psr/psr-4.md
      - PSR 5: psr/psr-5.md
      - PSR 6: psr/psr-6.md
      - PSR 7: psr/psr-7.md
      - PSR 8: psr/psr-8.md
      - PSR 9: psr/psr-9.md
      - PSR 10: psr/psr-10.md
  - API:
      - Pilar-pilar API: api/pilar-pilar-api.md
      - Framework API: api/framework-api.md
      - Struktur Dasar API: api/struktur-dasar-api.md
      - Metode HTTP: api/metode-http-api.md
      - Format Response API: api/format-response-api.md
  - Python:
      - PEP8: python/pedoman.md
      - FastAPI: python/praktik.md
      - Dokumentasi API: python/integrasi.md
  - Dokumentasi:
      - Dokumentasi: dokumentasi-content.md
      - Changelog: changelog-content.md
  - Database:
      - Intro Database: database/intro.md
      - Basis Data: database/penamaan-db.md
      - Struktur Tabel: database/penamaan-table-view-dll.md
      - Penamaan Field: database/penamaan-field.md
      - Data Staff & Student: database/database-staff-student.md
      - Transaksi & Referensi: database/aturan-data-transaksi-referensi.md
  - API Gateway:
      - Pengantar API Gateway: api_gateway/pengantar.md
      - Krakend sebagai API Gateway: api_gateway/karakend_api_gateway.md
      - Menggunakan Krakend: api_gateway/menggunakan_krakend.md
      - Fungsi Lain dari Krakend: api_gateway/fungsi_lain_krakend.md
      - Flexibel Configuration: api_gateway/krakend_fastapi.md
  - DEVOPS: devops.md
  - Contact: contact.md
