site_name: UGM Framework Guideline
site_description: Pedoman pengembangan sistem di UGM
site_url: http://dti.ugm.ac.id
site_author: Task Force UGM Framework DTI UGM
theme:
  name: material
  palette:
    primary: indigo
  logo: assets/ugmfw.png
  icon:
    repo: fontawesome/brands/gitlab
  favicon: assets/favicon.ico
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.progress
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.path
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - toc.follow
plugins:
  - search
  - blog
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
repo_url: https://git.dev.ugm.ac.id/ugmfw/guidelines
repo_name: ugmfw/guidelines
extra:
  generator: false
  version:
    provider: mike
copyright: Copyright &copy; 2024 Universitas Gadjah Mada | Made with ❤️ and ☕ by Direktorat Teknologi Informasi.
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - Beranda:
      - UGM Framework: index.md
      - Tujuan: tujuan.md
      - Penutup: closing.md
  - Arsitektur & Prinsip:
      - Arsitektur Sistem: arsitektur-prinsip/arsitektur-sistem.md
      - Prinsip Dasar Pengembangan: arsitektur-prinsip/prinsip-dasar-pengembangan.md
      - Konsistensi Teknologi: arsitektur-prinsip/konsistensi-teknologi.md
      - Clean Code: arsitektur-prinsip/clean-code.md
  - PHP:
      - Intro: psr/intro.md
      - PSR 1 Coding Standart: psr/psr-1.md
      - PSR 12 Coding Style: psr/psr-12.md
      - PSR 4 Autoloader: psr/psr-4.md
      - PSR 3 Logger Interface: psr/psr-3.md
      - PSR 7 HTTP Message Interface: psr/psr-7.md
      - PSR 15 HTTP Handlers: psr/psr-15.md
      - PSR 17 HTTP Factories: psr/psr-17.md
      - PSR 18 HTTP Client: psr/psr-18.md
      - PSR 11 Container Interface: psr/psr-11.md
      - PSR 13 Hypermedia Links: psr/psr-13.md
      - PSR 6 Caching Interface: psr/psr-6.md
      - PSR 16 Simple Cache: psr/psr-16.md
      - PSR 14 Event Dispatcher: psr/psr-14.md
      - PSR 5 PHPDoc Standard: psr/psr-5.md
      - PSR 19 PHPDoc Tags: psr/psr-19.md
      - PSR 20 Clock: psr/psr-20.md
  - API:
      - Pilar-pilar API: api/pilar-pilar-api.md
      - Framework API: api/framework-api.md
      - Struktur Dasar API: api/struktur-dasar-api.md
      - Metode HTTP: api/metode-http-api.md
      - Format Response API: api/format-response-api.md
      - Data Validation & Sanitization: api/validasi-sanitasi.md
      - Pagination, Filtering, & Sorting: api/pagination-filtering-sorting.md
      - Keamanan: api/security-api.md
      - Scopes: api/scopes.md
      - Versioning Database: api/orm-database.md
      - Cache: api/cache-api.md
  - API Gateway:
      - Intro: api-gateway/intro.md
      - KrakenD:
          - Apa itu KrakenD?: api-gateway/karakend_api_gateway.md
          - Menggunakan KrakenD: api-gateway/menggunakan_krakend.md
          - Fungsi Lain dari KrakenD: api-gateway/fungsi_lain_krakend.md
          - Flexibel Configuration: api-gateway/krakend_fastapi.md
  - Python:
      - PEP8: python/pedoman.md
      - FastAPI: python/praktik.md
      - Dokumentasi API: python/integrasi.md
  - Dokumentasi:
      - Dokumentasi: dokumentasi/dokumentasi-content.md
      - Changelog: dokumentasi/changelog.md
      - Pre-release: dokumentasi/pre-release.md
      - Semantic Versioning: dokumentasi/semantic-versioning.md
      - Commit: dokumentasi/commit.md
      - Kesimpulan: dokumentasi/kesimpulan.md
  - Database:
      - Intro Database: database/intro.md
      - Basis Data: database/penamaan-db.md
      - Struktur Tabel: database/penamaan-table-view-dll.md
      - Penamaan Field: database/penamaan-field.md
      - Data Staff & Student: database/database-staff-student.md
      - Transaksi & Referensi: database/aturan-data-transaksi-referensi.md
  - DevOps: devops/devops.md
  - Tools:
      - Intro: tools/intro.md
      - Dev Tools:
          - PHPStorm (Education Version): tools/phpstorm.md
          - WebStorm (Education Version): tools/webstorm.md
          - PyCharm (Education Version): tools/pycharm.md
          - Visual Studio Code (VS Code): tools/vscode.md
      - Database:
          - SQL YOG (Enterprise Edition): tools/sqlyog.md
          - Navicat Premium: tools/navicat.md
          - DBeaver Community: tools/dbeaver.md
          - pgAdmin: tools/pgadmin.md
          - DBDiagram: tools/dbdiagram.md
      - Local Server Development:
          - Laragon: tools/laragon.md
          - PHP Built-in Server: tools/php-built-in-server.md
      - API:
          - Postman: tools/postman.md
          - Swagger: tools/swagger.md
          - Redoc: tools/redoc.md
      - Desain:
          - Figma (Education Version): tools/figma.md
      - Analisis:
          - Miro (Education Version): tools/miro.md
          - Draw.io: tools/draw.io.md
      - Dokumentasi:
          - Notion: tools/notion.md
          - MkDocs: tools/mkdocs.md
  - Keamanan:
      - Intro: security/intro.md
      - Celah Keamanan:
          - Intro: security/intro-celah-keamanan.md
          - SQL Injection: security/sql-injection.md
          - Cross-site Scripting: security/cross-site-scripting.md
          - Cross-site Request Forgery: security/cross-site-request-forgery.md
          - Path Traversal: security/path-traversal.md
          - Command Injection: security/command-injection.md
          - Broken Access Control: security/broken-access-control.md
          - Sensitive Data Exposure: security/sensitive-data-exposure.md
      - Pengujian Keamanan:
          - Intro: security/intro-pengujian.md
          - Static Application Security Testing: security/sast.md
          - Dynamic Application Security Testing: security/dast.md
  - User Interface:
      - Intro: ui-guidelines/intro.md
      - Tujuan: ui-guidelines/tujuan.md
      - Identitas Visual: ui-guidelines/identitas-visual.md
      - Komponen UI: ui-guidelines/komponen-ui.md
      - Layout: ui-guidelines/layout.md
      - Pembaharuan & Pemeliharaaan: ui-guidelines/pembaharuan-pemeliharaan.md
  - Kontak: contact.md
