site_name: UGM Framework Guideline
theme:
  name: material
  palette:
    primary: indigo
  logo: assets/ugmfw.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
repo_url: https://git.dev.ugm.ac.id/ugmfw/guidelines
extra:
  generator: false
  version:
    provider: mike
copyright: Copyright &copy; 2024 Direktorat Teknologi Informasi - Universitas Gadjah Mada.
nav:
  - Home: index.md
  - UGM API: api.md
  - Contact: contact.md
